EVG-13654: Introduce toggling functionality in PublicKeyForm
evergreen-ci/spruce pull request #1116
Opened 2022-02-24 15:46 UTC by minnakt

[EVG-13654](https://jira.mongodb.org/browse/EVG-13654), [EVG-16383](https://jira.mongodb.org/browse/EVG-16383)

### Description 
This PR implements the functionality where the user toggles between using an existing key or adding a new key (i.e. they can only see one at a time, mutually exclusive).

It also fixes the problem where the Event Log link on the `SpawnHostTable` was taking up too much space.

### Screenshots
https://user-images.githubusercontent.com/47064971/155555816-bbab6373-f6d7-4317-9e72-4d6a03ab6b17.mov

### Testing 
- Modified Cypress test in `spawn/host.ts`
- Modified unit tests in `PublicKeyForm.test.tsx`

2022-02-25 15:21 UTC, minnakt commented on src/pages/spawn/spawnHost/spawnHostModal/PublicKeyForm.tsx
> +  z-index: ${zIndex.tooltip};
Just a note: `popoverZIndex` on Select does NOT work for some reason so I had to use traditional CSS 🧍

2022-02-28 23:47 UTC, khelif96 requested changes

2022-02-28 23:47 UTC, khelif96 commented on src/components/styles/StyledLink.tsx
> +  width: fit-content;
What does this for?

2022-02-28 23:47 UTC, khelif96 commented on src/components/styles/StyledLink.tsx
> +  width: fit-content;
Would it make sense to apply this just to the link element we are targeting instead of making it universal to all links?

2022-02-28 23:47 UTC, khelif96 commented on src/pages/spawn/spawnHost/spawnHostModal/PublicKeyForm.tsx
> -import React, { useReducer } from "react";
I'm still encountering the issue i ran into when i tried to do this. 
<img width="670" alt="image" src="https://user-images.githubusercontent.com/4605522/156076299-1f9fd82b-d8ba-4c3c-8a1d-8103a44ddd3b.png">


The dropdown collides with the lg check box.

2022-02-28 23:47 UTC, khelif96 commented on src/pages/spawn/spawnHost/spawnHostModal/PublicKeyForm.tsx
> +  height: 48px;
Is this height necessary?

2022-02-28 23:47 UTC, khelif96 commented on src/pages/spawn/spawnHost/spawnHostModal/PublicKeyForm.tsx
> +  }, [selectState]); // eslint-disable-line react-hooks/exhaustive-deps
Would it make sense to default to an existing public key if one exists?

2022-03-01 16:50 UTC, khelif96 approved these changes

2022-03-01 21:46 UTC, merged