EVG-16456: Prevent polling on hidden pages
evergreen-ci/spruce pull request #1143
Opened 2022-03-09 18:35 UTC by minnakt

[EVG-16456](https://jira.mongodb.org/browse/EVG-16456)

### Description 
This PR makes it so that we don't poll for queries on hidden pages (e.g. if a user has a Spruce tab open but they aren't actively looking at that tab, we shouldn't poll for queries).

This PR:
- defines a new hook `usePageVisibility.ts` which is used to detect if a page is being viewed or not
- defines a new hook `usePollForQueries.ts` which uses `useNetworkStatus` and `usePageVisibility` to determine whether or not we should be polling for queries
- replaces all instances of `useNetworkStatus` with `usePollForQueries`, because the former no longer determines polling status

### Screenshots
 No visible changes 

### Testing 
- Modified unit tests for `useNetworkStatus.test.ts`
- Added unit tests for `usePageVisibility.test.ts`
- Added unit tests for `usePollForQueries.test.ts`

2022-03-09 19:04 UTC, sophstad requested changes
Ahhh, so this is why you've been "💬 turning my internet off and on for a ticket"

This is super cool!!

2022-03-09 19:47 UTC, minnakt commented on src/hooks/tests/useNetworkStatus.test.ts
>      expect(result.current).toBe(false);
I agree it's a little weird... I added some documentation and switched this hook to return `isOnline`, so online corresponds true (which is more what I would expect). Let me know if that's still not intuitive 😅

2022-03-09 23:07 UTC, khelif96 approved these changes
Great work on this! I'm excited to see how noticeable the impact on evergreen will be! Some users have as many as 10 tabs of spruce open at any given time. So this could have a potential 10x reduction in load on evergreen

2022-03-10 15:17 UTC, sophstad approved these changes

2022-03-11 02:57 UTC, merged