EVG-16584: Upgrade Jest and react-testing-library
evergreen-ci/spruce pull request #1310
Opened 2022-06-03 13:23 UTC by SupaJoon

[EVG-16584](https://jira.mongodb.org/browse/EVG-16584)

### Description 
Upgrade jest and react-testing-library
`@testing-library/react` and `@testing-library/user-event` are behind one major version and should be bumped when we upgrade to react v18

2022-06-06 15:29 UTC, sophstad requested changes

2022-06-06 15:29 UTC, sophstad commented on package.json
> +    "@leafygreen-ui/leafygreen-provider": "^2.2.0",
Are these updates necessary now that we're not updating Code to v11? [9.1.0](https://github.com/mongodb/leafygreen-ui/blob/main/packages/code/CHANGELOG.md#910) has no dependency updates.

2022-06-06 15:29 UTC, sophstad commented on package.json
> +    "@leafygreen-ui/palette": "^3.3.2",
Same as above.

2022-06-06 15:29 UTC, sophstad commented on package.json
> +    "jest": "^28.1.0",
We have been using pinned dependencies for Jest and some of the other packages, is there any reason we can't continue doing that?

2022-06-07 18:47 UTC, sophstad approved these changes

2022-06-07 21:45 UTC, khelif96 requested changes

2022-06-07 21:45 UTC, khelif96 commented on package.json
> +    "jest-circus": "^28.1.0",
Why are we installing jest-circus? 
<img width="851" alt="image" src="https://user-images.githubusercontent.com/4605522/172486641-8acced7b-3a6c-4b5a-8d7b-e064fbb4a16f.png">
https://www.npmjs.com/package/jest-circus

2022-06-07 21:45 UTC, khelif96 commented on package.json
> +    "@testing-library/react-hooks": "8.0.0",
wow 5 major versions!

2022-06-07 21:45 UTC, khelif96 commented on src/jestResolver.js
> +      }
https://github.com/uuidjs/uuid/pull/616#issuecomment-1111000582
Does this work instead?

This seems safer than deleting  exports from the package.

2022-06-10 15:04 UTC, khelif96 approved these changes
Assuming tests pass LGTM

2022-06-10 15:27 UTC, merged