EVG-18835: Don't access property of undefined
evergreen-ci/spruce pull request #1641
Opened 2023-01-31 19:12 UTC by SupaJoon

[EVG-18835](https://jira.mongodb.com/browse/EVG-18835)

2023-01-31 22:15 UTC, khelif96 requested changes

2023-01-31 22:15 UTC, khelif96 commented on src/components/PatchesPage/PatchCard.tsx
> +      `${projectMetadata?.owner}/${projectMetadata?.repo}`
While this temporarily alleviates the issue it doesn't get at the real cause. This results in these values being undefined. 
<img width="881" alt="image" src="https://user-images.githubusercontent.com/4605522/215895480-82742b13-5cb5-46aa-a9de-ae42269222c5.png">

Ideally, we should  try to understand why these values are undefined in the first place. 

Looks like we are missing both  `projectIdentifier` and `projectMetadata`.

2023-02-01 14:54 UTC, minnakt commented
More pointers that might help: I noticed that these `undefined` values will show when a repo patch has not been configured. Repo patches that have been configured will properly show the owner and repo. This sort of makes sense to me as an unconfigured patch does not have a corresponding version, so if you try to get the `projectMetadata` from it, it will be null.

<img width="243" alt="Screen Shot 2023-02-01 at 9 51 25 AM" src="https://user-images.githubusercontent.com/47064971/216076258-1a2a594b-8464-4d33-9f00-7337030b376b.png">

Also I have a feeling that the project identifier is supposed to be null, otherwise why would we have the fallback in the first place. 🤔

2023-02-14 19:13 UTC, khelif96 approved these changes

2023-02-15 14:39 UTC, merged