EVG-18797: Make Hosts table Owner control always visible
evergreen-ci/spruce pull request #1642
Opened 2023-01-31 19:48 UTC by SupaJoon

[EVG-18797](https://jira.mongodb.com/browse/EVG-18797)

2023-01-31 22:17 UTC, khelif96 requested changes

2023-01-31 22:17 UTC, khelif96 commented on src/pages/hosts/HostsTable.tsx
> +  word-break: break-all;
You can reuse the word break style we already have
https://github.com/evergreen-ci/spruce/blob/620562260a9e06b7996671a45e9ab33f9f2399cf/src/components/styles/Typography.tsx#L11

2023-02-01 15:11 UTC, minnakt approved these changes
Aside from Mohamed's comment, I think wrapping the Current Task column in `WordBreak` would also be helpful because it frequently overflows its assigned width.

Also if you wanted to redistribute the width percentages I wouldn't be opposed to it!

2023-02-07 22:55 UTC, khelif96 approved these changes
LGTM

2023-02-07 22:55 UTC, khelif96 commented on src/pages/hosts/HostsTable.tsx
> +      width: "17%",
nit.  This comment is more so about my personal feelings toward "magic numbers" as opposed to an actual complaint.  How would this look if we used more rounded numbers? Like maybe 15% and 20% (on line 171)

2023-02-08 14:32 UTC, merged