EVG-18525: Replace Antd Popconfirm
evergreen-ci/spruce pull request #1725
Opened 2023-03-09 20:57 UTC by sophstad

EVG-18525

### Description

- Replace Antd's popconfirm with our own implementation

### Screenshots

### Testing

### Evergreen PR

2023-03-13 17:47 UTC, khelif96 requested changes
Great job taking this on!

While I do agree the tooltip serves our needs, making it interactable goes against leafy greens design guidelines. 

https://www.mongodb.design/component/tooltip/guidelines/#:~:text=Never%20nest%20call%20to%20actions%20within%20tooltips.
> Never nest call to actions within tooltips.

2023-03-13 17:47 UTC, khelif96 commented on src/components/Popconfirm/index.tsx
> +    (typeof active === "boolean" && setActive) || uncontrolledSetOpen;
Can you explain this type check? 
couldn't you do this?
```suggestion
    (active === null" && setActive) || uncontrolledSetOpen;
```

2023-03-13 17:47 UTC, khelif96 commented on src/components/Popconfirm/index.tsx
> +  return popoverContent;
```suggestion
  const triggerClickHandler = (e: React.MouseEvent) => {
    if (open) {
      onCancel();
    }

    setOpen(!open);
    trigger?.props?.onClick?.(e);
  };

  const renderedTrigger =
    trigger !== undefined &&
    cloneElement(trigger, {
      ref: triggerRef,
      onClick: triggerClickHandler,
    });

  return (
    <>
      {renderedTrigger}
      {popoverContent}
    </>
  );
```

2023-03-13 19:01 UTC, sophstad commented
> While I do agree the tooltip serves our needs, making it interactable goes against leafy greens design guidelines.

@khelif96 I noticed this too, but I feel like what we're doing by using the Popover here is effectively going against the guideline anyway. We're not _technically_ using Tooltip for an interaction, but we're effectively doing the same thing. Those guidelines also refer to mouseover instead of click interactions, so I wonder if they're a little outdated. Interested in any other thoughts on this!

2023-03-13 19:26 UTC, khelif96 commented
> > While I do agree the tooltip serves our needs, making it interactable goes against leafy greens design guidelines.
> 
> @khelif96 I noticed this too, but I feel like what we're doing by using the Popover here is kinda going against the guideline anyway. We're not _technically_ using Tooltip for an interaction, but we're effectively doing the same thing. I think it's a reasonable UX pattern regardless! Those guidelines also refer to mouseover instead of click interactions, so I wonder if they're a little outdated. Interested in any other thoughts on this!

That is a good point I would be curious to hear from the design folks if they have any opinions on it. But it does look like cloud does use popover to define similar interactions like this. 
https://github.com/search?q=repo:10gen/mms+@leafygreen-ui/popover&type=code
while the few tooltip usages I found did not define any interactivity. (Although I didn't look at all of them)
https://github.com/search?q=repo:10gen/mms+@leafygreen-ui/tooltip&type=code&p=2

2023-03-13 20:17 UTC, sophstad commented
> That is a good point I would be curious to hear from the design folks if they have any opinions on it. But it does look like cloud does use popover to define similar interactions like this. https://github.com/search?q=repo:10gen/mms+@leafygreen-ui/popover&type=code while the few tooltip usages I found did not define any interactivity. (Although I didn't look at all of them) https://github.com/search?q=repo:10gen/mms+@leafygreen-ui/tooltip&type=code&p=2

Sounds good, I added to design sync for this week since this would make sense as a followup ticket anyway. Thanks!

2023-03-13 20:58 UTC, sophstad commented on src/components/Popconfirm/index.tsx
> +  onConfirm?: (e?: React.MouseEvent) => void;
`onConfirm` is called when the "ok" button is clicked, what kind of handler were you thinking of?

2023-03-15 21:55 UTC, khelif96 approved these changes
SGTM

2023-03-16 15:55 UTC, sophstad commented
evergreen retry

2023-03-16 18:07 UTC, merged