EVG-19057: Set and render external links
evergreen-ci/spruce pull request #1729
Opened 2023-03-14 15:04 UTC by SupaJoon

[EVG-19057](https://jira.mongodb.com/browse/EVG-19057)

### Description
These code changes allow users to set external links from the plugins page to render in the version metadata panel

<img width="831" alt="Screenshot 2023-03-27 at 10 17 39 AM" src="https://user-images.githubusercontent.com/10734386/227967415-4f1326ea-6b52-4192-b494-0b87fa837434.png">
<img width="301" alt="Screenshot 2023-03-27 at 10 18 27 AM" src="https://user-images.githubusercontent.com/10734386/227967416-3b257387-16b0-472b-8c76-40a2132855cc.png">

2023-03-15 21:01 UTC, minnakt requested changes
this is really cool!

2023-03-16 15:27 UTC, khelif96 requested changes

2023-03-16 15:27 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +  });
In this case, can we remove the assignment to destination if it's only used by `cy.visit` the variable assignment doesn't seem necessary.

2023-03-16 15:27 UTC, khelif96 commented on src/pages/projectSettings/tabs/PluginsTab/PluginsTab.tsx
> +  const urlTemplateDefined = !!patchMetadataPanelLink.urlTemplate.trim();
Just for clarity could we make this a little more verbose?

2023-03-16 15:27 UTC, khelif96 commented on src/pages/projectSettings/tabs/PluginsTab/getFormSchema.ts
> +                title: "Display name",
```suggestion
                title: "Display name",
                maxLength: 40
```

2023-03-16 15:27 UTC, khelif96 commented on src/pages/projectSettings/tabs/PluginsTab/PluginsTab.tsx
> +  }
RJSF can handle this automatically if you pass in the maxLength property to this field in the schema definition.

2023-03-16 15:27 UTC, khelif96 commented on src/pages/projectSettings/tabs/PluginsTab/PluginsTab.tsx
> +  if (patchMetadataPanelLink.displayName.length > 40) {
This can likely be handled by rjsf as well.
https://rjsf-team.github.io/react-jsonschema-form/docs/usage/dependencies/#schema-dependencies

2023-03-16 17:57 UTC, khelif96 commented on src/utils/validators/index.ts
> +  return validateUrlRegex.test(formattedURL);
```suggestion
  return validateURL(formattedURL);
```

2023-03-16 18:05 UTC, khelif96 commented on src/utils/validators/index.ts
> +  /^(https?:\/\/(www\.)?|ftp:\/\/(www\.)?|www\.){1}([0-9A-Za-z-.@:%_+~#=]+)+((\.[a-zA-Z]{2,3})+)(\/(.)*)?(\?(.)*)?/;
This url regex is a little much it looks like it accepts FTP URLs and that's not something we would expect in the app. 

Have you seen this approach? 
https://www.freecodecamp.org/news/how-to-validate-urls-in-javascript/

2023-03-16 19:11 UTC, minnakt approved these changes
nice work!!

2023-03-27 14:24 UTC, ablack12 approved these changes

2023-03-27 17:22 UTC, merged