EVG-19044: Add guidance to priority settings
evergreen-ci/spruce pull request #1840
Opened 2023-05-19 16:35 UTC by minnakt

EVG-19044

### Description
This PR surfaces a warning when users try to set their patch or task priority to any value greater than 50.

### Screenshots
<img width="463" alt="Screenshot 2023-05-19 at 12 15 38 PM" src="https://github.com/evergreen-ci/spruce/assets/47064971/6bf468ae-b712-45bb-aea0-1dde84bcd1d7">

### Testing
- Add tests in `SetPriority.test.tsx`

2023-05-19 21:14 UTC, khelif96 requested changes

2023-05-19 21:14 UTC, khelif96 commented on src/components/SetPriority/index.tsx
> +            type="number"
I get these number increment buttons.
<img width="227" alt="image" src="https://github.com/evergreen-ci/spruce/assets/4605522/6227fe63-9244-430e-a450-c0565ccf11b3">

2023-05-19 21:14 UTC, khelif96 commented on src/components/SetPriority/index.tsx
> +export const SetPriority: React.VFC<SetPriorityProps> = ({
You can build some type safety into this with the following type

```ts
type SetPriorityProps = (
  | {
      patchId: string;
      taskId?: never;
    }
  | {
      taskId: string;
      patchId?: never;
    }
) & {
  initialPriority?: number;
  disabled?: boolean;
};
```

2023-05-19 21:14 UTC, khelif96 commented on src/components/SetPriority/index.tsx
> +export const SetPriority: React.VFC<SetPriorityProps> = ({
nit. default export?

2023-05-22 14:12 UTC, minnakt commented on src/components/SetPriority/index.tsx
> +const TextInput = styled(TextInputWithGlyph)<{ warning: boolean }>`
changed the component!

2023-05-22 22:21 UTC, khelif96 approved these changes
Great Refactor!

2023-05-24 21:20 UTC, merged