EVG-6689: Add unconfigured patch status badge
evergreen-ci/spruce pull request #1841
Opened 2023-05-22 19:30 UTC by SupaJoon

[EVG-6689](jira.mongodb.com/browse/EVG-6689)

### Description
![Screenshot 2023-05-23 at 2 30 33 PM](https://github.com/evergreen-ci/spruce/assets/10734386/a45684d6-3771-41e8-834f-03911df4deff)

2023-05-22 21:11 UTC, ablack12 commented
Should we show unconfigured _instead of_ created? It kind of doesn't mean anything with that in mind. 

Re [our conventions](https://docs.google.com/document/d/1LJHPjLb_bUZxv-l_9Y61kitzAg7u-13I5DjOhZ-deBA/edit#heading=h.i9oftc5069w9) here we should have a verb in PR titles indicate what's actually happening (like "add unconfigured patch status badge")

Also, is it incidental that app is requested here rather than ui?

2023-05-23 14:27 UTC, ablack12 commented
The design that Minna shows in EVG-6689 does show just Unconfigured; I don't think this is a reasonable patch status for the backend though, and would be a massive change --can this be done on the front end without that? Adjusting the filter dropdown to created/unconfigured seems fine though. 

>Since non commit queue patches are shown alongside regular patches 
this sentence doesn't super make sense to me since non commit queue patches _are_ regular patches, is this a typo? Having mixed statuses is fine I think -- commit queue patches don't need configuring so showing created there would be correct.

2023-05-24 20:45 UTC, khelif96 requested changes

2023-05-24 20:45 UTC, khelif96 commented on src/components/PatchesPage/PatchCard.tsx
> +            <PatchStatusBadge status={versionFull?.status ?? status} />
I think some change here broke the alignment
Before:
<img width="948" alt="image" src="https://github.com/evergreen-ci/spruce/assets/4605522/8a196ffa-56e9-4825-bfe7-2c8e9831f0ca">

After:
<img width="423" alt="image" src="https://github.com/evergreen-ci/spruce/assets/4605522/dc734b6b-8fed-430b-b4b4-af4a1b8f4fec">

2023-05-25 14:46 UTC, khelif96 commented on src/components/PatchStatusBadge.tsx
> +  unconfigured: Variant.LightGray,
Can you leave a comment here?

2023-05-25 14:46 UTC, khelif96 commented on src/components/PatchesPage/PatchCard.tsx
> +          {isUnconfigured && <PatchStatusBadge status="unconfigured" />}
```suggestion
          <PatchStatusBadge
            status={
              isUnconfigured ? "unconfigured" : versionFull?.status ?? status
            }
          />
```

2023-05-25 14:46 UTC, khelif96 commented on src/utils/patch/index.ts
> +  !activated && alias !== commitQueueAlias;
nit. This function might read better as  
`isPatchConfigurable`.

2023-05-25 14:46 UTC, khelif96 commented on src/components/PatchesPage/StatusSelector.tsx
> +          : noFilterMessage
Nice!

2023-05-25 16:18 UTC, khelif96 approved these changes
Great job!

2023-05-25 16:57 UTC, merged