EVG-20710, EVG-20911: Isolate project_settings tests
evergreen-ci/spruce pull request #2056
Opened 2023-09-21 17:46 UTC by SupaJoon

EVG-20710
EVG-20911

2023-09-26 18:18 UTC, minnakt commented on cypress/integration/projectSettings/project_settings.ts
> +      cy.wait(200);
Have you explored changing the frontend logic so that the page only loads when the project and repo settings queries are complete?

2023-09-26 18:18 UTC, minnakt commented on cypress/integration/projectSettings/project_settings.ts
> +describe("Access page", () => {
Is it possible to move this one to its own file `access.ts`?

2023-09-26 18:18 UTC, minnakt commented on cypress/integration/projectSettings/project_settings.ts
> +describe("Repo Settings", () => {
Is it possible to move this to its own file `repo_settings.ts`?

2023-09-26 18:24 UTC, khelif96 requested changes

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +    cy.get("[aria-label='Username'").as("usernameInput").type("admin");
We have a method for this called `cy.getInputByLabel` https://github.com/evergreen-ci/spruce/blob/c80310a696663d5d1cc1ec45506f26b83849153a/cypress/support/e2e.ts#L79

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +    cy.get("[aria-label='Internal Access']")
same label comment

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +    cy.reload();
Can you explain what you mean by assert persistence?

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +  describe("General settings pag", () => {
```suggestion
  describe("General settings page", () => {
```

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +          .should("be.visible");
```suggestion
        cy.dataCy("error-banner")
          .contains(
            "A Commit Check Definition must be specified for this feature to run."
          )
          .as("errorBanner")

        cy.get("@errorBanner")
          .should("be.visible");
```

I think this reads better and breaks up the variable assignment from the assertion.

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +    cy.get("[aria-label='Username'").as("usernameInput").type("admin");
Same comment about breaking it up as well!

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +          .should("be.visible");
Same comment!

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +        .should("not.be.checked");
same comment.

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +      cy.contains("label", "Add to GitHub Trigger Alias").click();
Use getInputBylabel here or the alias you created above.

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +      // Fix duplication
What does this comment mean?

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +      cy.reload();
Same question about these reloads?

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +      cy.wait(100);
Can we assert on some variable or element changing? This tends to lead to flakiness if an action takes longer than this timeout.

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +      cy.wait(200);
Can you add an assertion that checks that the button changed to the state we expected it to?

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +      cy.get('[aria-label="Git Clone"]')
`getInputByLabel`

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +        .as("gitCloneButtonContainer")
also same comment about breaking this up.

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +    xit("Shows warnings about enabling PR Testing", () => {
You may have accidentally muted this test.

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +    xit("Doesn't show a warning about enabling commit checks because the feature is disabled", () => {
Same comment.

2023-09-26 18:24 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +    xit("Shows a warning about enabling commit queue", () => {
same comment.

2023-10-02 18:30 UTC, khelif96 commented
@SupaJoon can you rebase this pr and the EVG-19395-feature-branch branch off of main? There are a ton of commits that should not be here which makes it difficult to review

2023-10-02 18:55 UTC, minnakt approved these changes
great job!

2023-10-02 18:55 UTC, minnakt commented on src/pages/projectSettings/index.tsx
> +    project;
Can this be rewritten as 
```suggestion
    const hasLoaded = !projectLoading && !repoLoading && project;
```
where `repoLoading` was added to the repo query? I ran a test patch [here](https://spruce.mongodb.com/version/651b0aff3627e0ac130b54ad/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).

2023-10-02 18:55 UTC, minnakt commented on src/pages/projectSettings/index.tsx
> +    project;
If not, I think I would at least prefer
```suggestion
  const hasLoaded =
    (projectData ||  projectType === ProjectType.Repo) &&
    (repoData || projectType === ProjectType.Project) &&
    project;
```

2023-10-02 18:55 UTC, minnakt commented on cypress/integration/projectSettings/project_settings.ts
> +      .should("be.enabled");
probably want to check `aria-disabled` instead due to LG's quirks

2023-10-02 19:50 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +      cy.contains("label", "Add to GitHub Trigger Alias").click();
I do agree that Leafygreens "fake checkbox" implementation isn't ideal. I think I would still prefer that we use the same pattern we use elsewhere in the code base. It is more readable and clear what we are trying to check and assert on the same checkbox element.  
```suggestion
            cy.get("@triggerAliasCheckbox").check({ force: true });
```

2023-10-02 19:50 UTC, khelif96 commented on cypress/integration/projectSettings/project_settings.ts
> +      );
```ts
      cy.getInputByLabel("Override Repo Patch Aliases").should("be.checked");
```

2023-10-03 19:12 UTC, khelif96 approved these changes
👏

2023-10-03 19:22 UTC, merged