EVG-12929 Create feedback component
evergreen-ci/spruce pull request #405
Opened 2020-09-15 23:01 UTC by khelif96

This adds a feature requests link to the bottom of all pages that takes the user to uservoice. 
A new `.cmdrc.json` is needed to test
![image](https://user-images.githubusercontent.com/4605522/93273392-bb1a5e80-f785-11ea-93a9-08f9466965ee.png)

2020-09-16 14:00 UTC, SupaJoon commented
<img width="1680" alt="Screen Shot 2020-09-16 at 9 45 47 AM" src="https://user-images.githubusercontent.com/10734386/93347240-d8414280-f802-11ea-9c43-82781c413eae.png">
I think it's inconvenient that the feedback label covers a patch name. A solution I can think of is to create a static footer that spans the the bottom of the page and have rest of the page contents rendered above it

2020-09-16 14:06 UTC, SupaJoon requested changes
I think it's inconvenient that the label covers a patch name. A solution that could work is to render the label in a footer and have all of the other page contents render above.

<img width="1680" alt="Screen Shot 2020-09-16 at 9 45 47 AM" src="https://user-images.githubusercontent.com/10734386/93348499-463a3980-f804-11ea-92ab-c0069f7b1bd8.png">

2020-09-16 14:06 UTC, bsamek commented
Would it be better to put this at the bottom right? That tends to be the least information dense part of the page.

2020-09-16 20:20 UTC, khelif96 commented on src/components/Feedback/index.tsx
> +  const userVoiceUrl = `https://feedback.mongodb.com/forums/${getUserVoiceKey()}`;
https://github.com/evergreen-ci/evergreen/pull/3995/files

2020-09-17 01:51 UTC, john-m-liu approved these changes

2020-09-17 18:18 UTC, SupaJoon approved these changes

2020-09-21 16:04 UTC, merged