EVG-12988  bb Jira URL should be queried from the db since it is configurable
evergreen-ci/spruce pull request #426
Opened 2020-09-25 15:08 UTC by malikchaya2

2020-09-25 17:42 UTC, khelif96 requested changes
There Seems like theres a ton of prop drilling to get the jira host to the component that its needed in. I dont necessarily feel that this url should be included in the build baron query since its so general, and we likely would reuse it again. I think It might make more sense to include it as apart of the spruceConfig query https://github.com/evergreen-ci/evergreen/blob/master/graphql/schema.graphql#L734

2020-09-25 18:21 UTC, john-m-liu approved these changes

2020-09-29 15:37 UTC, SupaJoon commented
We can use the jira host by querying the SpruceConfig: https://github.com/evergreen-ci/evergreen/blob/master/graphql/schema.graphql#L735
https://github.com/evergreen-ci/evergreen/blob/master/graphql/schema.graphql#L735

2020-09-29 16:01 UTC, khelif96 approved these changes

2020-09-29 16:23 UTC, merged