EVG-13300 show PR commit queue items
evergreen-ci/spruce pull request #491
Opened 2020-10-27 18:41 UTC by ablack12

![image](https://user-images.githubusercontent.com/26798134/97346872-67aa2e80-1862-11eb-88ef-bd9d6ecae95b.png)

2020-10-28 14:16 UTC, john-m-liu requested changes
Looks good but can you add a test for a PR commit queue? You'll probably need to do the following
- add a project with a pr commit queue + its corresponding commit queue to the testdata/local data in evergreen. Can probably enable it for the logkeeper project
- add a cypress integration test here that visits the url for that commit queue and asserts that certain elements are there

2020-10-28 14:50 UTC, malikchaya2 reviewed
This looks great! Should be gtg after tests.

2020-10-28 14:50 UTC, malikchaya2 commented on src/gql/generated/types.ts
> +  RemoveItemFromCommitQueue?: Maybe<Scalars["String"]>;
once you change this to camelcase in Evergreen, you'll have to `npm run codegen` again to change it here.

2020-10-28 15:55 UTC, SupaJoon commented on src/pages/commitqueue/CommitQueueCard.tsx
> +  const [RemoveItemFromCommitQueue, { loading, error }] = useMutation<
nit: we usually make this variable camel case

2020-10-28 16:35 UTC, SupaJoon commented
You can ignore the failing `test` and `coverage` tasks because they are flakey at the moment

2020-10-28 17:27 UTC, khelif96 commented
in order to resolve the `package-lock` merge conflict delete the file and run `npm install` .

2020-10-29 18:55 UTC, khelif96 commented
Sorry should have clarified. Merge master, delete the file, then run npm install to regenerate it.

2020-10-29 18:56 UTC, khelif96 commented
Actually on second thought the file should not have changed at all since did not make any changes to any dependencies. or else package.json would have changed too.

2020-11-02 21:46 UTC, john-m-liu approved these changes

2020-11-02 22:38 UTC, merged