EVG-13314 Wire up clear all subscription button
evergreen-ci/spruce pull request #514
Opened 2020-11-03 18:44 UTC by khelif96

2020-11-04 19:19 UTC, SupaJoon requested changes
The Clear all subscriptions button should actually remove the subscriptions created by clicking on "notify me" on the version and task pages. I created a PR for the corresponding mutation here: https://github.com/evergreen-ci/evergreen/pull/4137

2020-11-04 23:58 UTC, khelif96 commented
> The Clear all subscriptions button should actually remove the subscriptions created by clicking on "notify me" on the version and task pages. I created a PR for the corresponding mutation here: [evergreen-ci/evergreen#4137](https://github.com/evergreen-ci/evergreen/pull/4137)

Thanks!

2020-11-05 17:41 UTC, SupaJoon approved these changes

2020-11-05 17:41 UTC, SupaJoon commented on src/pages/preferences/preferencesTabs/notificationTab/ClearSubscriptionsCard.tsx
> +            To clear all subscriptions you have made on individual Task pages.
can we change this copy to "To clear all subscriptions you have made on individual Version and Task pages."?
relevant thread: https://mongodb.slack.com/archives/G013M6ULWS1/p1604515687002100

2020-11-05 17:41 UTC, SupaJoon commented on src/pages/preferences/preferencesTabs/notificationTab/ClearSubscriptionsCard.tsx
> +        `Successfully cleared ${result.clearMySubscriptions} subscriptions!`
These code changes work well. Can pluralize "subscriptions" based on `result.clearMySubscriptions`

2020-11-05 20:20 UTC, merged