EVG-12889: prevent showing LOADING... when the browser doesn't have an evg cookie
evergreen-ci/spruce pull request #563
Opened 2020-12-23 18:12 UTC by SupaJoon

the [first PR](https://jira.mongodb.org/browse/EVG-12889) in [EVG-12889](https://jira.mongodb.org/browse/EVG-12889) exposed an issue where a user can get stuck seeing the FullPageLoad component when they are unauthenticated with a cookie. 
These code changes fix that issue by: 
a) no longer relying on the initialLoad variable
b) moving redirect logic to async function calls

2020-12-23 18:16 UTC, SupaJoon commented on src/components/Content/index.tsx
> -        <PrivateRoute path={routes.task} component={Task} />
I removed the PrivateRoute component since we have an  `isAuthenticated` condition in this render function body.

2020-12-23 19:58 UTC, malikchaya2 approved these changes

2020-12-24 00:33 UTC, khelif96 requested changes
I dont think the behavior should have changed. Can we revert it back to its original behavior. This was likely from a recent commit.

2020-12-24 00:33 UTC, khelif96 commented on cypress/integration/auth.ts
> +  it("Redirects user to My Patches page after logging in.", () => {
Why did this change? I think we should still preserve the previous route after a successful login

2021-01-11 16:38 UTC, khelif96 commented
Can you merge master?

2021-01-11 16:54 UTC, khelif96 commented
https://user-images.githubusercontent.com/4605522/104212680-76d15f00-5403-11eb-9038-3829d5bfa3f8.mov

I merged in the latest master and pushed to staging. I think theres something wrong with the redirect logic. Starting in the graphql playground i confirmed that i was able to make requests. But when i try to load spruce on staging it ends up showing the loading screen and then forcing a redirect back to legacy evergreen

2021-02-01 17:31 UTC, SupaJoon commented
evergreen retry

2021-02-01 17:41 UTC, khelif96 approved these changes

2021-02-01 18:06 UTC, merged