EVG-13653 EVG-13720 Handle Tasks with multiple executions and
evergreen-ci/spruce pull request #592
Opened 2021-01-11 23:39 UTC by khelif96

Show correct logs for tasks with multiple executions.
Reduce unnecessary requests and renders for task executions. 
Cleanup code

2021-01-12 16:13 UTC, john-m-liu requested changes
I think we should have a test with a task log that has more than 1 execution. If the main effort behind that is test data, DM me and I can send you something

2021-01-12 16:17 UTC, malikchaya2 reviewed
It looks like there is a type in the pr title

2021-01-12 20:58 UTC, khelif96 commented
> It looks like there is a typo in the pr title

Thanks it got cut off

2021-01-12 21:09 UTC, malikchaya2 commented
> Thanks it got cut off

also EVG-13653 EVG-13720

2021-01-12 21:18 UTC, khelif96 commented
> > Thanks it got cut off
> 
> also EVG-13653 EVG-13720

That part is correct its covering both tickets

2021-01-12 21:33 UTC, john-m-liu approved these changes

2021-01-14 22:09 UTC, khelif96 commented
evergreen retry

2021-01-19 18:11 UTC, SupaJoon commented on src/pages/task/logs/LogTypes.tsx
> +                key={`${d.resourceId}_${d.id}_${index}`} // eslint-disable-line react/no-array-index-key
it may be okay to omit `${d.resourceId}_${d.id}_` and rely on index only since we don't expect list elements to change order

2021-01-19 18:28 UTC, SupaJoon commented on cypress/integration/task_route.ts
> +  it("shoul not be redirected if they land on a task page with a tab supplied", () => {
nit: typo

2021-01-19 18:28 UTC, SupaJoon approved these changes

2021-01-19 22:22 UTC, merged