EVG-14073 fix annotation note metadata styling
evergreen-ci/spruce pull request #661
Opened 2021-02-22 18:05 UTC by ablack12

![image](https://user-images.githubusercontent.com/26798134/108750073-96819a00-750e-11eb-8955-e27dcdc364f6.png)

2021-02-22 19:58 UTC, khelif96 approved these changes

2021-02-22 20:01 UTC, khelif96 commented
The tests are failing can you please update this test along side this pr. https://github.com/evergreen-ci/spruce/blob/82684a550fe376bf2661be5fb74c4cd911941707/cypress/integration/project/patches.ts#L24
I think the patch name just needs to be updated

2021-02-22 20:08 UTC, malikchaya2 requested changes
I don't know how easy it is to accomplish this, but I think ideally we should try to leave less space between the two things displayed, and not wrap the line (closer to how it's shown on the design). I also noticed that the the time and author are flipped from what the design shows. Was that done on purpose (either seem fine to me)?
![image](https://user-images.githubusercontent.com/13104717/108763783-c4bba580-751f-11eb-9064-48a010817b80.png)

2021-02-22 21:08 UTC, ablack12 commented
> I don't know how easy it is to accomplish this, but I think ideally we should try to leave less space between the two things displayed, and not wrap the line (closer to how it's shown on the design). 

I tweaked it a little bit (and tweaked the ticket metadata, which also wraps pretty frequently). If the name was even _longer_ than this it could still wrap, but for the regular case this will look better (also if the name is any longer than this I'll be really impressed haha).
![image](https://user-images.githubusercontent.com/26798134/108770241-110ae380-7528-11eb-9a2f-706b0ba4d65d.png)

> I also noticed that the the time and author are flipped from what the design shows. Was that done on purpose (either seem fine to me)?

This was done on purpose, in order to more closely match the jira ticket metadata, and was discussed at the time.

2021-02-22 21:32 UTC, ablack12 commented
> I think the patch name just needs to be updated

@khelif96 it looks like the patch isn't on that page; I'm not sure what would've changed but? I removed it.

2021-02-22 22:31 UTC, malikchaya2 approved these changes

2021-02-23 14:56 UTC, ablack12 commented
https://github.com/evergreen-ci/evergreen/pull/4422 this should fix the spruce test; @khelif96 can I merge?

2021-02-23 15:03 UTC, khelif96 commented
> [evergreen-ci/evergreen#4422](https://github.com/evergreen-ci/evergreen/pull/4422) this should fix the cypress test; @khelif96 can I merge?

Can you merge the test data fixes and try to rerun the tests?

2021-02-23 15:35 UTC, khelif96 commented on cypress/integration/project/patches.ts
>        "dist",
```suggestion
      "Commit Queue Merge:"
      "dist",
```

2021-02-23 17:28 UTC, merged