EVG-13859 Create Project Select component
evergreen-ci/spruce pull request #686
Opened 2021-03-15 12:24 UTC by khelif96

Check it out in storybook or on the commits page `localhost:3000/commits/evergreen`

2021-03-15 17:35 UTC, SupaJoon commented on src/pages/commits/ProjectSelect.tsx
> +    (project) => !favoriteIdentifiers.includes(project.identifier)
this presents a difficult ux since `.includes` case sensitive. can we use regex to make a looser match?

2021-03-15 17:36 UTC, SupaJoon commented on src/pages/commits/ProjectSelect.tsx
> +            {filteredProjects.map((p) => (
filteredProjects could be null

2021-03-15 18:05 UTC, SupaJoon requested changes
there is a type error when i interact with the project select component on this page http://localhost:3000/commits/rast

2021-03-15 19:33 UTC, khelif96 commented
> there is a type error when i interact with the project select component on this page http://localhost:3000/commits/rast

I'm unable to replicate this could you send a screenshot?

2021-03-17 15:35 UTC, SupaJoon commented
> > there is a type error when i interact with the project select component on this page http://localhost:3000/commits/rast
> 
> I'm unable to replicate this could you send a screenshot?

I think you fixed it here: https://github.com/evergreen-ci/spruce/pull/686/commits/572e0ff256747c3f04634ab5d651bde6265c3fdb#diff-8007d47f454b4fe0d720795efe248a552a7b5bb9900aea0f8622095170145c3aL103

2021-03-17 15:35 UTC, SupaJoon approved these changes

2021-03-17 16:13 UTC, merged