EVG-14664
evergreen-ci/spruce pull request #759
Opened 2021-05-27 20:06 UTC by bynn

![image](https://user-images.githubusercontent.com/26491602/119890109-6975c680-bf05-11eb-9da9-6b0075b7ad2e.png)
![image](https://user-images.githubusercontent.com/26491602/119890143-785c7900-bf05-11eb-94a4-b777b7e001be.png)

2021-06-02 18:37 UTC, SupaJoon commented on src/pages/spawn/spawnHost/EditSpawnHostButton.tsx
> +          console.log(openTooltip);
left over log

2021-06-02 18:55 UTC, bynn commented on src/pages/spawn/spawnHost/EditSpawnHostButton.tsx
> +          console.log(openTooltip);
done

2021-06-03 14:36 UTC, SupaJoon requested changes

2021-06-03 16:23 UTC, SupaJoon commented
your e2e test failure was an io issue and all test specs passed. i restarted the e2e task to see if it happens again

2021-06-03 16:24 UTC, SupaJoon approved these changes

2021-06-03 17:13 UTC, khelif96 requested changes

2021-06-03 17:13 UTC, khelif96 commented on src/pages/spawn/spawnHost/EditSpawnHostModal.tsx
>              >
Same comment here

2021-06-03 18:22 UTC, SupaJoon commented
created this ticket to address the failing test https://jira.mongodb.org/browse/EVG-14742

2021-06-04 18:21 UTC, bynn commented on src/pages/spawn/spawnHost/EditSpawnHostButton.tsx
>          >
done

2021-06-04 18:21 UTC, bynn commented on src/pages/spawn/spawnHost/SpawnHostButton.tsx
> +      </span>
done

2021-06-04 18:21 UTC, bynn commented on src/pages/spawn/spawnHost/EditSpawnHostModal.tsx
>              >
done

2021-06-08 22:05 UTC, khelif96 approved these changes
Great Job LGTM!

2021-06-09 14:09 UTC, merged