EVG-14618: Sort execution tasks
evergreen-ci/spruce pull request #776
Opened 2021-06-08 19:44 UTC by sophstad

[EVG-14618](https://jira.mongodb.org/browse/EVG-14618)

### Description 
< add description, context, thought process, etc >

### Screenshots
 < add screenshots of visible changes >

### Testing 
  < add a description of how you tested it >

### Evergreen PR 
  < link to a corresponding evergreen PR if applicable >

2021-06-11 15:00 UTC, SupaJoon requested changes

2021-06-14 16:11 UTC, khelif96 requested changes

2021-06-14 16:11 UTC, khelif96 commented on src/pages/task/TaskTabs.tsx
> +import { toSortString } from "pages/patch/patchTabs/util";
Can you please move this to a generic util folder. If we need something from another page it should be moved to a more generic folder.

2021-06-14 16:11 UTC, khelif96 commented on src/pages/task/TaskTabs.tsx
> +              [RequiredQueryParams.Execution]: "0",
We can't hardcode execution since tasks can have multiple executions this will cause it to always show the first one.

2021-06-16 19:08 UTC, khelif96 approved these changes

2021-06-16 19:57 UTC, SupaJoon requested changes
I think we need to add weights/sort instructions for the antd status column. 
We do this for the PatchTasks query for the other Tasks table here: https://github.com/evergreen-ci/evergreen/blob/92438f2eac2677e38a8738e9be5cc914aba3b0c6/model/task/task.go#L2938-L2980
I think currently the antd table will use alphabetical sorting by default and the status order ascending will look like this: ```["aborted", "blocked", "dispatched", "failed", "inactive", "known-failure", "pending", "setup-failed", "started", "success", "system-failed", "system-timed-out", "system-unresponsive", "task-timed-out", "test-timed-out", "undispatched", "unstarted"]```

Alphabetical sorting is really close to the weights we use in the db query except for statuses like 'system-failed' which should be alongside other "failed" statuses. 

I think it's okay if we hardcode the weights client side to resemble what we are doing in the PatchTasks resolver to avoid additional resolver changes or add sort params to the executionTasksFull resolver.

2021-06-17 16:19 UTC, SupaJoon approved these changes

2021-06-17 18:02 UTC, merged