EVG-14876: Background Grid for Commit Charts
evergreen-ci/spruce pull request #802
Opened 2021-07-02 14:18 UTC by ziyielenachen

[EVG-14876](https://jira.mongodb.org/browse/EVG-14876)

### Description 
Added background lines for the commits wrapper

### Screenshots
<img width="1440" alt="Screen Shot 2021-07-02 at 10 12 07 AM" src="https://user-images.githubusercontent.com/55669681/124287948-9a59a480-db1e-11eb-90d1-ee47c31f57aa.png">

2021-07-02 14:26 UTC, malikchaya2 reviewed
Can you please add a screenshot of the design as well?

2021-07-02 14:28 UTC, malikchaya2 commented on src/pages/commits/commitChart/Grid.tsx
> +    <DashedLine />
Can we maybe have a separated component that we can pass a number to, for example 5, and have it render that many lines?

2021-07-06 15:09 UTC, SupaJoon requested changes

2021-07-06 15:09 UTC, SupaJoon commented on src/pages/commits/commitChart/Grid.tsx
> +      <DashedLine />
DashedLine needs a unique `key` prop. You can see a warning about it the console when we render this component

2021-07-06 19:56 UTC, SupaJoon approved these changes

2021-07-06 20:00 UTC, merged