EVG-14964 Fix Known-Issue only appearing after a second
evergreen-ci/spruce pull request #844
Opened 2021-08-11 20:25 UTC by malikchaya2

[EVG-14964 ](https://jira.mongodb.org/browse/EVG-14964 )

### Description 
when clicking into a task and then using the back button, there is a second where we load bad data until the new request refreshes it. Instead, we want to wait and only show the data once the query is done loading. 

### Testing 
tested on staging to make sure the bug is gone with this fix.

2021-08-11 21:28 UTC, khelif96 requested changes
Discussed offline, But also commenting here for visibility.  This eliminates the usability of the apollo cache since we are waiting for a response before we render any data. This is especially apparent when trying to use the table pagination. 
https://user-images.githubusercontent.com/4605522/129105500-9b687a58-43f5-4bc6-944a-1f4674e07400.mov

We can try to set the [no-cache](https://www.apollographql.com/docs/react/data/queries/#no-cache) fetch policy on the task query to avoid overwriting the cache for this field.

2021-08-12 15:13 UTC, khelif96 requested changes

2021-08-12 15:30 UTC, malikchaya2 commented on src/components/PatchTabs/Tasks.tsx
> +    fetchPolicy: "no-cache",
setting no-cache on Task.tsx doesn't fix the bug, but this does. :(

2021-08-12 16:33 UTC, khelif96 requested changes
Discussed offline. This ended up breaking  the cache more. :(

2021-08-12 18:41 UTC, malikchaya2 commented
> Discussed offline. This ended up breaking the cache more. :(

Yes. Hacking the cache is hard. I will try a backend approach instead.

2021-08-23 17:09 UTC, closed without merging