EVG-13226: align logo
evergreen-ci/spruce pull request #967
Opened 2021-11-05 15:15 UTC by SupaJoon

[EVG-13226](https://jira.mongodb.org/browse/EVG-13226)

2021-11-05 16:37 UTC, khelif96 requested changes
I would push back on the need to do this ticket.
Both the logo and the nav items technically are centered relative to the nav. They just  don't appear centered relative to each other because they have different font-sizes and are positioned near each other. 

If you give them both the same font weight and size they are centered perfectly.
![image](https://user-images.githubusercontent.com/4605522/140545373-455d68c2-9e05-4b90-b906-20d0bf1d5eb1.png)

There is a hack that will allow you to center the nav  items with the logo. Even with different font sizes. You can give the nav items the same `line-height` as the logo and they will be centered automatically with the same positioning as the logo. But like i said i feel  that it's a bit of a hack. But i think its better than manually fine tuning the margins of the elements to get them to align perfectly.

2021-11-05 16:37 UTC, khelif96 commented on src/components/Header/Navbar.tsx
> +  margin-top: -3px;
now the logo isn't centered in the nav. :/

2021-11-08 14:10 UTC, SupaJoon commented
I moved this ticket into waiting to get feedback from design on whether we need the logo text at all.

2021-11-11 20:17 UTC, khelif96 approved these changes
Can we add some analytics to the other nav items. Just to understand what people are clicking?

2021-11-12 21:31 UTC, SupaJoon commented
> Can we add some analytics to the other nav items. Just to understand what people are clicking?

I created another ticket for this since it will require some modifications to Header/Dropdown.tsx
https://jira.mongodb.org/browse/EVG-15850

2021-11-15 15:13 UTC, merged